config/routes.rb
Rails.application.routes.draw do

  get "contact", to: "pages#contact"
  get "projects", to: "pages#projects"
  get "error", to: "pages#error"

  # get "blog", to: redirect("url")

 root 'pages#home'

 get "*path", to: redirect("/error")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def home
  end

  def projects
  end

  def error
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheLordOftheRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Exo+2" rel="stylesheet">
  </head>

  <body>
  <div id="main-title">
    <h1>The Lord of the Rails</h1>
  </div>
<div id="navbar">
  <div class="row">
    <div class="col-md-12">
      <ul class="nav">
        <li>
          <%= link_to "Home", root_path %>
        </li>
        <li>
          <%= link_to "Projects", projects_path %>
        </li>
        <li>
          <%= link_to "Contact", contact_path %>
        </li>
        <li class="dropdown pull-right open">
          <br /><br />
        </li>
      </ul>
    </div>
  </div>
</div>
<content>
  <div class="container-fluid">
    <div class="transbox">
      <%= yield %>
    </div>
  </div>
</content>
  </body>
</html>

app/views/pages/contact.html.erb
<div id="contact_style">
	<h1>How to get a hold of me</h1>
	<p>Please feel free to send me and email or give me a call regarding any questions or opportunities. Thanks!</p>
	<div id="conts">
		<h3>Phone</h3>
		<h4>480.202.9489</h4>
		<h3>Email</h3>
		<h4>dmcoley948562@gmail.com</h4>
		<h3>LinkedIn</h3>
		<a href="https://www.linkedin.com/in/daniel-coley-7154b4b0/" target='_blank'>Daniel Coley's LinkedIn profile</a>
	</div>
</div>

app/views/pages/error.html.erb
<h1>Sorry, that page does not exist :( </h1>

Go back to <%= link_to "homepage", root_path %>

app/views/pages/home.html.erb
<div id="homepage_style">	
	<div class="row">
		<div class="col-md-4">
			<h2>
				Who am I?
			</h2>
			<p>
				Hello! my name is Dan Coley. I'm a fullstack developer who's a board/video game enthusist. I love taking on challenges and pushing my self to the limit. I'm an Arizona native and I love to tinker and play golf.
			</p>
			
		</div>
		<div class="col-md-4">
			<h2>
				What do I know?
			</h2>
			<p>
				I have a good working knowledge of Ruby, Rails, HTML/CSS, Javascript, SQL, Angular 2, and Spanish. I have made it a piority to be very well rounded and be able to work back end profeciently as well as front end.
			</p>
			
		</div>
		<div class="col-md-4">
			<h2>
				Why do I do it?
			</h2>
			<p>
				I started coding after realizing I wanted a career that I could grow with and support my family. Though I initially just wanted the job security I have really grown to love what I'm learning and doing.
			</p>
			
		</div>
	</div>
</div>

app/views/pages/projects.html.erb
<div id="projects_style">
<div class="row">
		<div class="col-md-4">
			<h2>
				TheLordoftheRails
			</h2>
			<p>
				The site you are on right now! This is my rails project that use for my portfolio. Over time I will also add a video page where I can explain rails principles and people can ask questions. This site shows my proficiency in ruby, rails, html, and css.
			</p>
			<p>
				<a class="btn" href="https://github.com/DanielmColey/lordoftherails" target='_blank'>See the code »</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>
				Daily Smarty
			</h2>
			<p>
				This website clone is done in a blog format. Daily Smarty is a place where people can come to be informed on many topics from politics, sports, and even gaming. This was a fun project because it helped me understand a completely different style of formatting using HTML/CSS. 
			</p>
			<p>
				<a class="btn" href="https://github.com/DanielmColey/first-push/blob/master/clones/social_media.html" target='_blank'>See the code »</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>
				Ruby Challenges
			</h2>
			<p>
				Everyday I am faced with a prompt and have the opportunity to stretch my knowledge of ruby concepts. These are challenges from altering given data to creating a program from the ground up. These challenges are important to me because if forces me to think outside the box and invent new ways to solve issues.
			</p>
			<p>
				<a class="btn" href="https://github.com/DanielmColey/ruby-code/tree/master/Challenge" target='_blank'>See the code »</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>
				Overtime
			</h2>
			<p>
				This is an application using Ruby and Rails that allows salaried employees to track their overtime. The app doesn't just store the data but also allows Administrator access to approve or deny the overtime on a page that denies access to employees. Employees are notified through SMS to record their hours. This project was highly test driven using rspec. Username: test@test.com or admin@test.com Password: asdfasdf.
			</p>
			<p>
				<a href="https://github.com/DanielmColey/overtime-app" target='_blank'>See the code »</a>
				<a href="https://way-overtime.herokuapp.com/users/sign_in" target='_blank'>See the page »</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>
				Tesla Clone
			</h2>
			<p>
				This was my favorite clone project I took on. Though I had cloned websites before, there were aspects of this one that pushed my limits. I added a background image and learning how to format it and also making a footer with extra styling.
			</p>
			<p>
				<a href="https://github.com/DanielmColey/first-push/tree/master/clones/tesla_clone" target='_blank'>See the code »</a>
				<a href="https://www.flickr.com/photos/146949987@N03/32033000930/in/dateposted-public/" target='_blank'>See the page »</a>
			</p>
		</div>
		<div class="col-md-4">
			<h2>
				Google Clone
			</h2>
			<p>
				This was the first website I have ever cloned before. I was intimidated to take it on but it was an extremely pleasent suprise when I was able to turn out a very close replica. This project was actually what grew my love for HTML/CSS.
			</p>
			<p>
				<a class="btn" href="https://github.com/DanielmColey/first-push/blob/master/clones/google_clone.html" target='_blank'>See the code »</a>
			</p>
		</div>
	</div>
</div>